osx_image: xcode9
language: objective-c
xcode_project: NewCandySearch.xcodeproj
xcode_scheme: NewCandySearch
before_script:
- "./scripts/add-key.sh"
- "./scripts/update-bundle.sh"
- "./scripts/sign-and-upload.sh"
script:
- xcodebuild clean build -project NewCandySearch.xcodeproj -scheme NewCandySearch
  -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_script:
- "./scripts/remove-key.sh"
after_success:
- "./scripts/HockeySDK.sh"
env:
  global:
  - APP_NAME="ObjC-IOS"
  - DEVELOPER_NAME="Pfizer International Inc"
  - INFO_PLIST="NewCandySearch/Info.plist"
  - PROFILE_NAME="TCS_Distribution_Profile_16To17"
  - secure: aOa5uAIBgczT4p+cSgMlhX+Ia7lHS9h1t2zWvcRk0tHi3vX/xjDG8cEP46DRaOzVMkb/FvQp6h6SkvBGe01n2Cu6RM51pTZPkqBy1A+zN+xh2RmP94DQTI1aF00EguMRKwoZDE4W5s+Oiw8UQKVKPD0A0cqy2FzdGtXABS/UHEDY3Y3VKZKZFNHW2hFRcT4AwbCAGtvUyv2vjQDW33odHdQbAdXTAEtziTR2wIEAp2wnHDQcbY7pGw2NFx1FzxlYszUEacWrSYhURzvRn4sVRvBISRZ37lKs5cExwGb7ccyQk+pJB042vpssT7Dx9PjwO6iV2/M9mBiDUS1aqTGwR9TyYBA9bOhISC07kFxY5NhaftzPeqq9bZJGt5DKvA2Py5S4ASnEX3N0DZdEDo9F5oa6JkSXe7TaKRnSD3ZtcFjChdaIe2BpV29GDlHzmsRBWfU5GXT6h9sP4Af/PHPa2TuQ7qVeUv/rqXPClQI+G1EPqKj1yvZZNYukopyZlTbQ3eUoYeuQdUN3iBRepVaWkO6KiVPNFsDe8wVW7Apt4NGjwIlQhfOHI77JR0PxmJ1ANcmjia8fI9HSmwhrmNpC3EEBQMUFuXlj9tbgfIlqqVkm98UcHFFatssRHJHldYLmPPcCig6mgTmPQ0H60KrKvGez0btuJcZQm/aX5G+p8To=
  - secure: MZbodNXn5aE4Z21r0olDbX62fOJysG9qH2+cRa2JO0ZjV0qX+7YvCdhUY3GvQJIgSll3kBBjo0im72LLTOHK0hIy3jSjLqiU7ra1r4iqdMacqnBOfEn7gs/+rHdgw28H221TqwYyoWa+gqwXQ5AbaaWUSATSJTI20evjWJYHwFo/xQZNIpWBcoHFua33wqTuRn2C91gEW4Tdna+PjpWUMsq9MpDQptsfkzCBiDBOIw3AY8Cc1gUPxnLCfEQAwnMnVaUgEIdRIIxJjssxk4/WhISdOQgVfWi1Af9z33mSY6NI2CrF1XNs2/Ol6NY5T4UclXvQh+O4qEceiO9cYgHMfxeO2FyK0iC/4ozbs1AF4mdVgvfOct+6jp1c7upv5i6orQYdGvF2SYqtArnptT/k9HXDLkTdAqc5Ncq+sRl57alzAldBXVIAQkyK6xflyZETVEjxDQ8TpF5h9bqgdhz2Bwbw90pOmcE5M39Mwpb1vCuKYGZmCUKKZae5pRiCE4DmsdE1I0I+b4fO01Q+5L/HEC3J/ZZuGiQkKP3nmu75NbrK6qZIHB/8LlQ35qw8cXZxJHhaHpQWY6Sh9MSP8Y30JqS1nNm7h1mxGY8xgJjWdnvbcsR9LIOfSl10h/m+zTYWNFUvIDdjEJHf84fdKrvD4dEQNmE0AlKXdAvweVzpn2g=
  - secure: ds+Ek6e65f25/DgFTgaAZgM6yhqajNOQt1FnNB0XFBciFuuPCQ2YnTLJaNFtRT9j+p2FqpamnrM+sTlIo9bGQmGMuUyBUphua10QzQrotjkd0tJxwfrXHDMIFv68IQYF3+7YdmnjVFvBDmBF1RlaxmFqkA2UJxH1gBFtdoJPXZG7uf523ZTwW/sfRcQbr4L5MJC5lo+oLlee34p6Wga4tgXTjv68gSFaEFBA20yx5YwlaJ9sDelnPbSUrNKaC9tXrlXpXwwvZdpNCU+4S0g5xYgJDRQvVpjSO+fa7xa+XTLSY284LCgqHOSRxuw+zeCNRwCXbKBFvSIDAYjmZRttpUHSL5xPBLdHRsEEv411qhNMrSHUoaAilkFENyqdTuvOg2RSHm/D9kJwexguj7SXphAm2JBw1UAEcH2sPxinUnTXAEX4KMdVAI6kG3smnudmpQJRY4jl/mRcZ8MIqrHXYY2VEUbBc3EtH/Z0EM71SCqTxqyVroIOkoygxBFM/Cl/gg1TrasFrZx0yGGxH07NaIwxx0ZhtWPVcJ+uOr1FthX+AWaD6vjf2L41D6mkLpBp+s15Z8MNDq7at2YBBsvEDi1hQn2oA9tbBePP00vII+CdlpWXzY++K8tZZ/C3/iHvABfO3U8yoi5TKVpgJZVFQHeR/k+k5Jdydpxqr0Eh6Vo=
